// 
// FLTwoObjects.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/1/13 2:38 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp
// Schema: FLTwoObjects
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLTwoObjects.h"
@implementation FLTwoObjects
@synthesize object1 = _object1;
@synthesize object2 = _object2;
+ (FLTwoObjects*) twoObjects {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_object1 release];
    [_object2 release];
    [super dealloc];
}
#endif
@end
